README.md

Agrega paneles de seguimiento de tickets a fin de permitir el monitoreo
del proyecto.

Datos minimos de descripcion y seguimiento

---

View/Elements/menues/menu-sa.ctp

Ajusta menú por usuario según funcionalidades
Closes #19

fix(Vista): Delimita Menú

---

docker-compose.yml

Levanta contenedores para entorno docker lemp

build(Operaciones): Ajusta Docker Compose

---

Config/database.php

Se realizaron cambios sobre el archivo de configuración de la base de datos para que la aplicación se conecte a Mysql.

Modificacion sobre el archivo de configuracion de la base de datos.

---

Config/bootstrap.php
Controller/PersonasController.php
View/Elements/forms/form_persona_add.ctp
View/Elements/forms/form_persona_edit.ctp

Elimina el Plugin TinyMCE de la Aplicación y del Controlador y Vista de Persona.

fix($controladorVista): Elimina Plugin TinyMCE del Módulo Persona.

---

Controller/AlumnosController.php
Controller/AnexosController.php
Controller/CentrosController.php
Controller/DisenoCurricularsController.php
Controller/EmpleadosController.php
Controller/InscripcionsController.php
Controller/ResolucionsController.php
View/Elements/forms/form_alumno_add.ctp
View/Elements/forms/form_alumno_edit.ctp
View/Elements/forms/form_anexo.ctp
View/Elements/forms/form_centro.ctp
View/Elements/forms/form_disenocurricular.ctp
View/Elements/forms/form_empleado_add.ctp
View/Elements/forms/form_empleado_edit.ctp
View/Elements/forms/form_inscripcion.ctp
View/Elements/forms/form_resolucion.ctp

se elimino el plugin TinyMCE del helper de cada controlador, a cada vista se le elimino la llamada a dicho plugin.

elimina Plugin TinyMCE closed Issue #33

---

Model/Ciudad.php

Actualización del modelo:
Soluciona problemas de relaciones en las tablas. [Agrega relación con Barrio].

Agrega ciudad al modelo

---

docker-compose.override.yml

Utiliza la imagen de composer para correr migraciones al correr docker-compose up

build(operaciones): Corre migraciones automaticamente

---

docker-compose.override.yml
docker-compose.yml
docker/php-fpm/Dockerfile
docker/php-fpm/php-ini-overrides.ini

Closes #13
Resta implementar configuración nginx para aprovechar cache.

build(operaciones): Agrega memcache para seciones

---

Controller/PersonasController.php
Model/Asentamiento.php
View/Elements/forms/form_persona_add.ctp
View/Elements/persona.ctp

*Modificación sobre el controlador persona: se cargan los modelos necesarios para poder mostrar en las vistas la información relacionada a dichos modelos.
*Se ajustan las vistas de persona(index,add,edit) para mostrar la información de forma correcta.
*Se agrega al modelo "Asentamiento".
issue #42

Modifica controlador Persona, ajusta vistas y agrega Asentamiento

---

Config/Migration/1502401025_initial.php
Config/schema/schema.php

Modifica a motor InoDB y agrega los campos created y modified. Actualiza el Schema.php
Issue #67

fix($Base de Datos): Modifica motor y agrega campos

---

docker-compose.override.yml
docker-compose.yml
docker/php-fpm/Dockerfile
docker/php-fpm/php-ini-overrides.ini

Resuelve un problema de configuracion ocacionado por la confusion entre memcache y memcached

fix(operaciones): Fix memcached

---

docker/nginx/nginx.conf

perf(operaciones): Agrega memcached a nginx

---

Controller/AlumnosController.php
View/Elements/forms/form_alumno_add.ctp

Busca el nombre de una persona previamente creada.
El formulario aún no se encuentra completo, es necesario hacer las validaciones pertinentes antes de crear al Alumno.

Autocomplete #65

---

Controller/PersonasController.php
View/Elements/forms/form_persona_add.ctp
View/Elements/forms/form_persona_edit.ctp
View/Personas/listar_barrios_asentamientos.ctp

Se agrega:
*Selects dependientes a los formularios ADD y EDIT de persona.
*La clase "Listar_barrios_asentamientos.ctp".
*La función "ListarBarriosAsentamientos" en PersonasController.

Agrega selects dependientes

---

Config/Migration/1502977657_siep104516082017.php
Config/schema/schema.php
Controller/AlumnosController.php
Controller/CursosController.php
Controller/CursosInscripcionsController.php
Controller/InscripcionsController.php
Model/Centro.php
Model/Inscripcion.php
Model/Persona.php
Model/User.php
View/Centros/view.ctp
View/Cursos/view.ctp
View/Elements/centro.ctp
View/Elements/forms/form_curso.ctp
View/Elements/forms/form_inscripcion.ctp
View/Elements/forms/form_user_edit.ctp
View/Elements/formsSearch/formSearch_inscripcion.ctp
View/Elements/menues/menu-aip.ctp
View/Layouts/default.ctp

Modifica controladores y vistas para adecuar el ámbito a tipos de usuarios del nivel Inicial y Primaria.

Delimita ambito inicial primaria

---

Config/Migration/1502997632_siep041817082017.php
Config/schema/schema.php
Controller/CursosInscripcionsController.php

Agrega "Autoincrement" a todas las claves primarias.
Issue #67

fix($Schema): Agrega autoincrement a todas las claves primarias.

---

Controller/PersonasController.php
View/Elements/forms/form_persona_add.ctp
View/Elements/forms/form_persona_edit.ctp
View/Personas/listar_barrios_asentamientos.ctp

Corrección aplicada a los selects dependientes del formulario ADD y EDIT de persona.
Corrige el problema de guardado que tenian en la versión anterior.

corrección en selects dependietes

---

Controller/PersonasController.php
View/Personas/view.ctp

Corrige problemas conocidos en la vista "view->persona".
-Muestra el barrio o el asentamiento según la información almacenada en la base de datos.
-Agrega la ciudad a la vista.

Ajusta el View de persona

---

Controller/CentrosController.php
Model/Centro.php
Model/Departamento.php
View/Centros/view.ctp
View/Elements/centro.ctp
View/Elements/forms/form_centro.ctp

Issue #88:
* Se realizaron modificaciones en el modelo, se agrego la clase "Departamento".
*En el controlador de centros se cargaron los modelos necesarios para poder interactuar con las distintas vistas.
*Se adaptaron las vistas a los cambios recientes en el modelo.(revisión de los ComboBox y todos los elementos de las vistas[centro])

Adapta vistas a cambios en el modelo

---

Controller/CentrosController.php
Controller/EmpleadosController.php
Controller/PersonasController.php
View/Elements/forms/form_alumno_add.ctp
View/Elements/formsSearch/formSearch_alumno.ctp
View/Elements/formsSearch/formSearch_centro.ctp
View/Elements/formsSearch/formSearch_empleado.ctp
View/Elements/formsSearch/formSearch_persona.ctp

Autocomplete en:
-Instituciones
-Agentes
-Alumnos
-Personas

Agrega autocomplete

---

Controller/AppController.php
Controller/CentrosController.php
Model/Centro.php
View/Elements/forms/form_centro.ctp

*Se ajusto el formulario add de centros:
-Aplicación de selects dependientes a los combos --> departamento,ciudad y barrio.
-Aplicación de reglas de validación a los combos mencionados.(Para evitar errores cuando no se seleccione nada en el mismo)
*no se realizaron cambios en el AppController

Ajuste a la vista add de centro

---

Controller/AlumnosController.php
View/Elements/forms/form_alumno_add.ctp
View/Elements/forms/form_alumno_edit.ctp

Hay que tener en cuenta que se debe usar javascript para enviar
persona_id. 
Se aplican reglas de validacion.

Autocomplete en alumnos add/edit funciona correctamente.

---

Controller/PersonasController.php
View/Centros/view.ctp
View/Cursos/view.ctp
View/Elements/formsSearch/formSearch_curso.ctp
View/Elements/formsSearch/formSearch_cursosInscripcion.ctp
View/Elements/formsSearch/formSearch_persona.ctp
View/Elements/persona.ctp
View/Inscripcions/view.ctp
View/Personas/view.ctp

Continúa con la Delimitación del ámbito para el usuario de Inicial/Primaria planteado en el Issue #74 .

Agrega mas correcciones al branch

---

Model/Alumno.php
Model/Centro.php
Model/Ciclo.php
Model/Curso.php
Model/Inscripcion.php
Model/Materia.php
Model/Titulacion.php
Model/Titulo.php
Model/User.php
View/Elements/forms/form_ciclo.ctp
View/Elements/forms/form_titulacion.ctp

Se aplica reglas de validación en los modelos con el fin de evitar la carga de datos erróneos en los formularios(Evita inyección de datos no deseados en la BD, evita inyección SQL)
Corresponde al ISSUE #96

Agrega validaciones en el modelo

---

Controller/AlumnosController.php
View/Elements/forms/form_alumno_add.ctp

Alumno guarda correctamente a la persona_id.

Alumno guarda correctamente a la persona_id en al crear o editar.

---

Model/Persona.php
View/Elements/forms/form_inscripcion.ctp

*Ordenamiento de los elementos del formulario inscripción de alumno.
*Modificación en el modelo persona: se modificaron las reglas de validación para que el formulario add de persona funcione correctamente.

Corrección en formularios

---

Controller/CentrosController.php
Controller/MateriasController.php
Controller/TitulacionsController.php
Model/Titulacion.php
View/Elements/materia.ctp
View/Titulacions/view.ctp

Ajustes para la presentación a la SIT

---

Controller/AppController.php
Controller/CentrosController.php
Controller/CursosController.php
Controller/InscripcionsController.php
Controller/MatriculasController.php
Controller/TitulacionsController.php
Model/Curso.php
Model/Inscripcion.php
View/Cursos/view.ctp
View/Elements/forms/form_inscripcion.ctp
View/Elements/formsSearch/formSearch_titulacion.ctp
View/Elements/menues/menu-a.ctp
View/Elements/menues/menu-aip.ctp
View/Elements/menues/menu-sa.ctp
View/Matriculas/index.ctp

Actualiza en el DataTable los valores Matrícula y Vacantes de un curso determinado al producirse una
nueva inscripción. Según sea el usuario permite visualizar en el DataTable  los registros
correspondientes.
Issue #85

fix($DataTable): Actualiza Matrícula y Vacantes al incribir a un alumno.

---

Controller/MatriculasController.php
Controller/PasesController.php
Model/Alumno.php
Model/pase.php
View/Alumnos/view.ctp
View/Elements/forms/form_pase.ctp
View/Elements/pase.ctp
View/Pases/add.ctp
View/Pases/edit.ctp
View/Pases/index.ctp
View/Pases/view.ctp

AgregaMVCPase

---

Controller/MatriculasController.php
View/Matriculas/index.ctp

El datatable trae solo los datos necesarios, no adjunta todos los modelos relacionados y sus respectivos datos.
Solo falta aplicar la optimizacion cuando se accede a las Matriculas con el ROL Usuario.

Datatable Optimizado

---

Controller/PasesController.php
Model/Persona.php
View/Elements/pase.ctp
View/Elements/persona.ctp
View/Pases/view.ctp

Se implementa de forma parcial la vista a Pases.
Implementado: View,index.
Falta: Add, Edit.(En progreso)

implementa la vista a pases[parcial]

---

Controller/InscripcionsController.php
Controller/PersonasController.php
Model/Alumno.php
View/Elements/forms/form_inscripcion_add.ctp

Se agrego un autocomplete en inscripciones, busca Personas por DNI, Nombre y Apellido
Realiza un Alta automaticamente de la persona como  Alumno del CentroId

Optimizacion en Inscripciones/Add

---

Controller/PasesController.php
View/Elements/forms/pase_edit.ctp
View/Elements/pase.ctp
View/Pases/edit.ctp

*Corrección en la visualización de datos en "View", "Index".
*Ajuste en el funcionamiento del "Add" y "Edit".

Implementación de CRUD en pase

---

.gitignore
View/Elements/forms/form_inscripcion_add.ctp
View/Elements/formsSearch/formSearch_persona.ctp

Pequeña modificacion que permite buscar por Nombre Apellido y Dni
En form_inscripcion_add se modifica el selector de seccion por uno con formato de Tags

Formato de busqueda por persona

---

Controller/CursosInscripcionsController.php
Controller/InscripcionsController.php
Model/Inscripcion.php
View/Alumnos/view.ctp
View/Elements/forms/form_inscripcion_add.ctp
View/Elements/forms/form_inscripcion_edit.ctp
View/Elements/inscripcion.ctp
View/Elements/menues/menu-a.ctp
View/Elements/menues/menu-aip.ctp
View/Elements/menues/menu-sa.ctp
View/Elements/menues/menu-u.ctp
View/Inscripcions/view.ctp

Desde el MVC de Inscripciones se da de alta a una persona como alumno, se registra su Inscripción
y/o Pre-inscripción de ese alumno, se registra su baja y su egreso. Una vez registrada la
inscripción, se actualizan los valores "Matrícula" y "Vacantes" de la sección correspondiente.
Issue #133

fix($MVCInscripciones): Agrega funcionalidades al MVC Inscripciones

---

README.md

Agrega link a versión beta en el readme y el sitio

Agrega link a beta

---

Controller/AppController.php
Controller/CursosController.php
Controller/CursosInscripcionsController.php
Controller/InscripcionsController.php
Controller/PasesController.php
Model/Ciclo.php
Model/pase.php
View/Alumnos/view.ctp
View/Cursos/view.ctp
View/Elements/alumno.ctp
View/Elements/centro.ctp
View/Elements/curso.ctp
View/Elements/forms/form_inscripcion_edit.ctp
View/Elements/forms/form_pase_add.ctp
View/Elements/forms/form_pase_edit.ctp
View/Elements/formsSearch/formSearch_inscripcion.ctp
View/Elements/formsSearch/formSearch_pase.ctp
View/Elements/inscripcion.ctp
View/Elements/menues/menu-aip.ctp
View/Elements/pase.ctp
View/Inscripcions/view.ctp
View/Pases/add.ctp
View/Pases/edit.ctp
View/Pases/view.ctp

Agrega/Modifica MVC del Módulo de Pases.
Issue #127

fix(MVCPases): Define e implementa metodología de Pases.

---

.gitignore
Controller/MatriculasController.php
Controller/VacantesController.php
View/Elements/menues/menu-sa.ctp
View/Vacantes/index.ctp

Se agrega visualizacion de vacantes por seccion, solo en SuperAdmin por el momento
Faltan optimizar el filtro de busqueda, no permite realizar 2 busquedas simultaneas al pie de la tabla

Vacantes por seccion

---

Controller/AppController.php
Controller/CursosInscripcionsController.php
Controller/InscripcionsController.php
Controller/MatriculasController.php
Controller/PasesController.php
Model/Alumno.php
Model/Curso.php
Model/Inscripcion.php
Model/Persona.php
Model/pase.php
View/Elements/forms/form_alumno_add.ctp
View/Elements/forms/form_alumno_edit.ctp
View/Elements/forms/form_centro.ctp
View/Elements/forms/form_curso.ctp
View/Elements/forms/form_inscripcion_add.ctp
View/Elements/forms/form_inscripcion_edit.ctp
View/Elements/forms/form_pase_add.ctp
View/Elements/forms/form_pase_edit.ctp
View/Elements/forms/form_persona_add.ctp
View/Elements/forms/form_persona_edit.ctp

Quita Created de los formularios y cambia formato de dato en la base de datos para que  CakePHP lo
genere automáticamente.

fix($UsoDeCreated): Quita Created de los formularios.

---

Controller/AlumnosController.php
Controller/MatriculasController.php
View/Layouts/adminlte.ctp
View/Matriculas/index.ctp
View/Vacantes/index.ctp

Falta optimizar el buscador en vacantes

Dibujo de tabla en Matriculas y Vacantes

---

Controller/AlumnosController.php
View/Elements/alumno.ctp
View/Elements/formsSearch/formSearch_alumno.ctp

Fix varios, antes la busqueda de personas requeria de listar todos los alumnos de la DB, todos los DNI, para hacer un cruce en la vista., ahora el controlador devuelve la persona relacionada al alumno 1 a 1 
Mejoras varias en Autocomplete

Busqueda de alumnos optimizada

---

Controller/CursosInscripcionsController.php
Controller/GraficosController.php
Model/Curso.php
View/Elements/forms/form_curso.ctp
View/Elements/formsSearch/formSearch_curso.ctp
View/Elements/formsSearch/formSearch_cursosInscripcion.ctp
View/Elements/formsSearch/formSearch_pase.ctp
View/Graficos/index.ctp

Recorre y ajusta forms Search.

fix($FormSearch): Recorre y ajusta forms Search.

---

Controller/CentrosController.php
View/Elements/formsSearch/formSearch_centro.ctp
View/Elements/formsSearch/formSearch_persona.ctp
View/Helper/SiepHelper.php

La busqueda se puede realizar en Centro por Sigla o por CUE 
El autocomplete redirige automaticamente al id de la busqueda

Optimizacion de Persona y Centro

---

Controller/CursosController.php
Controller/InscripcionsController.php
Controller/PasesController.php
View/Matriculas/index.ctp
View/Pases/index.ctp

Ajusta ámbito de usuarios de secundaria.

fix($AmbitoDeUsuario): Ajusta ámbito de usuarios de secundaria.

---

Controller/InscripcionsController.php
View/Elements/forms/form_alumno_edit.ctp
View/Elements/forms/form_inscripcion_edit.ctp
View/Elements/formsSearch/formSearch_centro.ctp
View/Elements/formsSearch/formSearch_persona.ctp

Se modificaron para que el usuario precione en Buscar luego de seleccionar el resultado.
Inscripciones puede editar correctamente.
Hay que verificar el impacto en matriculas, tambien verificar al realizar un pase.

Forms de autocompletes en busquedas

---

Controller/AlumnosController.php
Controller/CursosController.php
Controller/InscripcionsController.php
Controller/PasesController.php
View/Elements/formsSearch/formSearch_pase.ctp
View/Elements/pase.ctp

fix($AmbitoDeUsuarios): Corrige Bugs.

---

Controller/PersonasController.php

Fix de select dependientes en Personas/Add

---

Controller/MatriculasController.php
View/Matriculas/index.ctp

Por el momento no funciona el filtro de ciclos, y en los select de Año y Division deberian ser del tipo unico para no repetir opciones.
El rol Admin no puede ver el autocomplete de secciones.

Filtros en Matriculas

---

docker/php-fpm/Dockerfile

Soluciona los problemas de permisos de cake durante la instalación.

Crea tmp/cache durante el build

---

Controller/CursosController.php
Controller/InscripcionsController.php
Controller/PersonasController.php
Controller/UsersController.php
Model/Curso.php
View/Centros/view.ctp
View/Elements/forms/form_ciclo.ctp
View/Elements/forms/form_curso.ctp
View/Elements/forms/form_inasistencia_add.ctp
View/Elements/forms/form_inasistencia_edit.ctp
View/Elements/forms/form_inscripcion_add.ctp
View/Elements/forms/form_inscripcion_edit.ctp
View/Elements/forms/form_integracion.ctp
View/Elements/forms/form_mesaexamen.ctp
View/Elements/forms/form_nota.ctp
View/Elements/formsSearch/formSearch_centro.ctp
View/Elements/formsSearch/formSearch_empleado.ctp
View/Elements/formsSearch/formSearch_persona.ctp
View/Inscripcions/view.ctp
View/Personas/index.ctp
View/Users/usuario.ctp

Agrega modificaciones en los formularios de Agregación y Edición para contemplar los registros de los diversos tipos de Inscripciones.

Ajusta PreInscripciones

---

Controller/MatriculasController.php
View/Matriculas/index.ctp

Si el usuario es administrador, el filtro no duplica los campos de año y division, ademas quita de la vista la opcion de elegir un centro.

fix(Filtro Matriculas)

---

Controller/MatriculasController.php

Al acceder a la URL matriculas/recuento
Se actualizan las matriculas y las vacantes de todas las inscripciones realizadas en todos los ciclos.

Recuento automatico de Matriculas

---

View/Elements/menues/menu-a.ctp
View/Elements/menues/menu-aip.ctp
View/Elements/menues/menu-sa.ctp
View/Vacantes/index.ctp

Ajusta visualizaciones del progreso de matrícula.
Issue #178

fix($Visualizaciones): Ajusta visualizaciones del progreso de matrícula.

---

Controller/VacantesController.php
View/Vacantes/index.ctp

Agrega columnas "Plazas" y "Matrículas" a la tabla de vacantes.

AjustaVacantes

---

Controller/CursosController.php
Controller/CursosInscripcionsController.php
Controller/InscripcionsController.php
Controller/VacantesController.php
View/Elements/forms/form_inscripcion_add.ctp
View/Elements/forms/form_inscripcion_edit.ctp
View/Elements/menues/menu-a.ctp
View/Elements/menues/menu-aip.ctp
View/Elements/menues/menu-sa.ctp
View/Elements/menues/menu-u.ctp
View/Vacantes/index.ctp

Ajusta impacto a matrícula y vacantes desde Inscripciones y agrega el impacto desde la modificación
de plazas en Curso.
#Issue 178

fix($MatriculayVacantes): Ajusta impacto a matrícula y vacantes.

---

View/Centros/index.ctp
View/Helper/SiepHelper.php

El helper de Siep->clearfix se encarga de optimizar el desplazamiento de las tarjetas.

Solucion al desplazamiento de tarjetas

---

View/Elements/forms/form_inscripcion_add.ctp

Falta procesar los datos del formulario en el controlador de Inscripcions/add

Tipo de alta dependiente

---

View/Elements/forms/form_disenocurricular.ctp

Modifica línea que llama al Plugins CakeUpload fuera de uso.

fix($Plugins): Corrige Bug Plugins

---

Controller/CentrosController.php
View/Alumnos/pdf/view.ctp
View/Alumnos/view.ctp
View/Centros/imprimir.ctp
View/Centros/view.ctp
View/Layouts/pdf.ctp
View/Layouts/pdf/default.ctp
View/Personas/pdf/view.ctp
View/Personas/view.ctp
View/Users/pdf/view.ctp

fix($Plugins): Quita lineas que usan CakePDF

---

Controller/InscripcionsController.php
Controller/MatriculasController.php
View/Elements/forms/form_inscripcion_add.ctp
View/Matriculas/index.ctp

Preparando Inscripciones y Matriculas para el laboratorio

Inscripcions/add && Matricula/index

---

Controller/CursosInscripcionsController.php
Controller/InscripcionsController.php
View/Elements/forms/form_inscripcion_add.ctp

Desactiva cursos "Sala de 3 años".
Modifica combobox "Secciones" del index de cursosInscripciones.

AjustesTallerInicialPrimaria

---

Controller/InscripcionsMateriasController.php

La columna Inscripcion.estado no existe, se cambio por Inscripcion.estado_inscripcion
Verificar su correcto funcionamiento

fix(InscripcionsMaterias)

---

webroot/css/custom.css

No se utilizaba, y realentizaba la carga de la pagina

GoogleFonts en custom.css removida

---

Controller/CursosInscripcionsController.php
Controller/FamiliarsController.php
Controller/VacantesController.php
View/Elements/forms/form_alumno_edit.ctp
View/Elements/forms/form_familiar.ctp
View/Elements/formsSearch/formSearch_cursosInscripcion.ctp
View/Elements/menues/menu-a.ctp
View/Elements/menues/menu-aip.ctp
View/Elements/menues/menu-sa.ctp
View/Elements/menues/menu-u.ctp
View/Familiars/view.ctp
View/Personas/view.ctp
View/Vacantes/index.ctp

Mejora accesibilidad en menúes, combobox. Inicia módulo de gestión de familiares.

AjustaMenuYCombobox

---

Controller/MatriculasController.php
Controller/VacantesController.php
View/Elements/forms/form_inscripcion_add.ctp
View/Matriculas/index.ctp
View/Vacantes/index.ctp

Combobox muestra por defecto ciclo actual y ultimo ciclo
Muestra el ciclo como un filtro en vacantes
Combobox de readonly a disabled

Matriculas por seccion y Vacantes agrupadas

---

View/Elements/forms/form_persona_add.ctp
View/Elements/menues/menu-a.ctp
View/Elements/menues/menu-aip.ctp
View/Elements/menues/menu-sa.ctp
View/Elements/menues/menu-u.ctp

Esconde opciones de carga en este módulo hasta no tanto se termine su desarrollo.

ComentaModuloFamiliares

---

Controller/CursosInscripcionsController.php
View/CursosInscripcions/index.ctp
View/Elements/cursosInscripcion.ctp
View/Elements/cursosInscripcion_lista.ctp
View/Elements/formsSearch/formSearch_cursosInscripcion.ctp

Desde el menu de busqueda es posible visualizar los alumnos por seccion en modo de lista.
Seria optimo poder ordenarlos por apellido, seleccionar las paginas a mostrar, y la posibilidad de exportar a Excel

Alumnos por seccion acepta modo lista

---

Controller/AlumnosController.php
Controller/FamiliarsController.php
Model/Alumno.php
Model/AlumnosFamiliar.php
Model/Familiar.php
View/Alumnos/view.ctp
View/Elements/forms/form_familiar.ctp
View/Elements/forms/form_inscripcion_add.ctp
View/Familiars/view.ctp

Issue #174 
Resta:
Ajustar selector de Alumnos.
Ajustar visualización de Familiares Relacionados en Alumnos.
Ajustar visualización de Alumnos Relacionados en Familiares.

AjustaModuloFamiliares

---

Config/core.php
Controller/AppController.php

Es necesario descomentar algunas lineas en estos 2 archivos para activar las lectura desde las variables de entorno

Variables de entorno

---

Config/core.php
Controller/AppController.php
chart/siep/templates/siep-php-fpm-deployment.yaml
chart/siep/values.yaml

Esto hace que el chart permita configurar el nivel de debug mediante values.yaml

Agrega env vars para configurar debug de Cake

---

View/Elements/cursosInscripcion_lista.ctp

Agrega búsqueda por columnas a lista. Issue #208

AgregaSortALista

---

Model/Persona.php
View/Elements/forms/form_persona_add.ctp
View/Elements/forms/form_persona_edit.ctp
View/Personas/view.ctp

Agrega la posibilidad de indicar la División Política del Lugar de Origen seleccionado para poder referenciar mejor el lugar de nacimiento de las personas extranjeras. Issue #165

AgregaCampoDivisionPolitica

---

Controller/FamiliarsController.php
View/Alumnos/view.ctp
View/Elements/menues/menu-a.ctp
View/Elements/menues/menu-aip.ctp
View/Elements/menues/menu-sa.ctp
View/Elements/menues/menu-u.ctp
View/Familiars/view.ctp

Ajusta visualizaciones de Familiares en Alumnos y de Alumnos en Familiares.
Falta modificar las selecciones múltiples en los formularios y el autocomplete en edit.
Issue #174

AjustaFamiliares

---

Controller/FamiliarsController.php
View/Elements/cursosInscripcion_lista.ctp
View/Elements/forms/form_familiar.ctp
View/Elements/forms/form_persona_add.ctp

Issue #174 
Resta:
- Mejorar búsqueda en el combobox múltiple de Alumnos.
- Modificar el autocomplete de Personas para que traiga los datos (en Edit).
- Modificar el autocomplete de Alumnos para los Supervisores.

AjustaPermisoEnFormFamiliar

---

.gitignore
Controller/InscripcionsController.php
View/Elements/forms/form_inscripcion_add.ctp

Falta forzar con javascript la seleccion del campo tipo de alta

Inscripcion/Add (Pases,Hermanos,Situacion social)

---

View/Elements/menues/menu-a.ctp
View/Elements/menues/menu-aip.ctp
View/Elements/menues/menu-sa.ctp
View/Elements/menues/menu-u.ctp

Agrega Familiares al Menú. Issue #174

AjustaMenuFamiliares

---

Controller/AlumnosController.php
Model/Curso.php
View/Elements/forms/form_curso.ctp
View/Elements/forms/form_inscripcion_add.ctp
View/Inscripcions/view.ctp
View/Users/index.ctp

(:) Agregar empleados y usuarios 
(:) Modificar/Agregar secciones agrupamientos en el Sabato y Guevara.listo (cuantos p/bachiller y p/tecnicos)
(:) Agregar personas ficticias.
(:) Agregar al view de inscripciones el nombre del alumno regular relacionado en inscripciones por hermanos.

AjustesParaSimulacro

---

Controller/InscripcionsController.php
View/Elements/forms/form_inscripcion_add.ctp
View/Elements/forms/form_inscripcion_edit.ctp

El campo edit obtiene el nombre de la persona, y no permite editarla.

fix(Inscripciones Add/Edit)

---

Controller/CentrosController.php
View/Elements/forms/form_inscripcion_add.ctp
View/Elements/forms/form_inscripcion_edit.ctp

Tipo Alta disabled en Inscripcion/Add
Inscripcion Add/Edit con select dependiente libreria Select2

Inscripcion Add/Edit Select Dependiente

---

Controller/VacantesController.php
View/Elements/cursosInscripcion_lista.ctp
View/Vacantes/index.ctp

Enlaces en vacantse y cursos

---

Controller/InscripcionsController.php
Model/Inscripcion.php

Desde el modelo de Inscripcion, se requiere el campo centro_id.
Corrige bug de memoria, valida Centro y Seccion

fix(Inscripcion/Add) Corrige bug de memoria

---

View/Elements/forms/form_inscripcion_add.ctp

Ajusta el formulario para la etapa de Inscripciones Comunes "No Confirmadas".

AjustaFormInscripcion

---

Controller/AlumnosController.php
Controller/FamiliarsController.php

Agrega recursive en finds para optimizar querys con el ORM de Cake.

ProbandoOptimizarFinds

---

Controller/VacantesController.php
View/Vacantes/index.ctp

La tabla de matriculas 2018 devuelve una suma de las inscripciones realizadas por hermano en ese curso y centro

Matriculas 2018 cuantifica hermanos

---

Controller/VacantesController.php

A travez de la url "vacantes/recuento" el sistema busca todos los agrupamientos para los diferentes centros cursos y divisiones, despues realiza un recuento de todas sus divisiones y las plasma en el agrupamiento correspondiente a esa division.

Recuento matricula 2018

---

Controller/InscripcionsController.php

Reestringe los permisos de agregación y edición de inscripciones a los usuarios "admin".

AjustaPermisosInscripcion

---

Model/Persona.php

Ajusta validación del campo "Lugar de Nacimiento" del modelo "Persona".

AjustaExpresionRegular

---

Controller/AppController.php
Controller/InscripcionsController.php

Optimiza la gestión de autorizaciones sobre las acciones del controlador de Inscripciones. 
Falta estructurarlo en un select y extenderlo al resto de los Controladores.

OptimizaGestionDeAutorizacionesEnInscripcion

---

Controller/CursosInscripcionsController.php

AjustesParaInicialyPrimaria

---

Controller/AppController.php
Controller/InscripcionsController.php

Revert "OptimizaGestionDeAutorizacionesEnInscripcion"

---

Controller/VacantesController.php

Agrega visualización de supervisión a "Alumnos por sección" y "Matrícula 2018".

AgregaAVerSupervisiones

---

Controller/CursosInscripcionsController.php

El rol usuario puede ver las inscripciones NO CONFIRMADAS, y al igual que el superadmin puede confirmar alumnos.

fix(CursosInscripciones)

---

Controller/CursosInscripcionsController.php

Rol admin tambien puede confirmar inscripciones

---

Controller/InscripcionsController.php

Prueba de Edición de las Inscripciones de los perfiles "superadmin" y "usuarios" cuando se modifica el centro.

AjustaEdicionInscripcion

---

View/Inscripcions/view.ctp

Constancia desde dominio externo

---

Controller/InscripcionsController.php
Controller/VacantesController.php
View/Helper/SiepHelper.php
View/Inscripcions/view.ctp

* Inscripcions permite add y edit al rol Admin
* Inscripcions/view muestra la constancia a los roles Usuario y Superadmin
* Vacantes genera un archivo log en la carpeta tmp/ para los usuarios definidos en el controlador.

Log en Vacantes

---

View/Cursos/view.ctp
View/Elements/curso.ctp

Permite visualizar en el index y view de secciones el tipo.

AgregaTipoEnSeccion

---

Controller/InscripcionsController.php

Quita permisos de agregación y edición a los usuarios admin.

QuitaPermisosAdmin

---

Controller/VacantesController.php
View/Vacantes/index.ctp

Se quita provisoriamente la visualización de esos valores de matrícula 2018 en el usuario admin de inicial y primaria.

Quita visualizacion de plazas y vacantes en admin de inicial y primaria

---

Controller/MatriculasController.php
Controller/VacantesController.php

Quita visualización de las secciones desactivadas en MATRÍCULA 2017 y en MATRÍCULA 2018.

Quita visualización de cursos Desactivados

---

Controller/PromocionController.php
View/Elements/formsSearch/formSearch_promocion.ctp
View/Elements/promocion_lista.ctp
View/Promocion/index.ctp

Falta definir la lógica, e incluir los enlaces en el front

Base de promocion

---

View/Vacantes/index.ctp

Para los niveles de servicio 
* Común - Inicial
* Común - Primaria
* Común - Inicial - Primaria

Se oculta plazas y vacantes

---

Controller/PromocionController.php
View/Cursos/view.ctp
View/Elements/promocion_lista.ctp
View/Promocion/index.ctp

Es necesario modificar la ruta de consumo de API en el controlador PromocionController metodo "confirmarAlumnos", lo ideal seria pasarlo por environment.

Consume API de Promocion

---

Controller/AppController.php

El metodo getTwoLastCicloNombres tenia una variable indefinida cuando no se cumplica el "if"

Fix AppController

---

Controller/PromocionController.php
View/Elements/promocion_lista.ctp

Evitar enviar promociones al año 2019

Fix en promocion

---

View/Cursos/view.ctp

Promocion solo para SuperAdmin

---

Controller/PromocionController.php
View/Cursos/view.ctp

Se agrega la variable de entorno para ver el API
Se muestra el boton promocionar para superadmin y usuario

Environment API y Show Boton promocion

---

Controller/PromocionController.php

Visualiza la variable de entorno HOSTAPI en los errores de consumo de API

API Visualizacion de Host en error

---

Controller/VacantesController.php
View/Cursos/view.ctp
View/Vacantes/index.ctp

Los datos cuantitativos solo visualizan el ciclo actual.
El boton promocionar se habilita para todos los roles

Datos cuantitativos en front, boton promocionar para admin

---

Controller/CursosInscripcionsController.php
View/Elements/formsSearch/formSearch_cursosInscripcion.ctp

Permite filtrar division solo a los usuarios admin
El modo lista se encuentra seleccionda por defecto
Pendiente division dependiente del centro seleccionado

Alumnos por seccion Filtros y Lista por defecto

---

Controller/CursosInscripcionsController.php
View/Elements/cursosInscripcion_lista.ctp

La exportacion se realiza desde alumnos por seccion. 
Es necesario definir centro_id y ciclo_id para que el boton se muestre.

Exportacion a excel de listas de alumnos

---

Controller/MatriculasController.php
View/Elements/cursosInscripcion_lista.ctp

Se fuerza a realizar el recuento solo para el ciclo 2018

Recuento 2018

---

Controller/PromocionController.php
View/Elements/promocion_lista.ctp

No permite la promoción de inscripciones en el ciclo actual. 
Muestra detalladamente los errores de la API

Promocion solo a los del ciclo anterior

---

Controller/CursosInscripcionsController.php
Controller/MatriculasController.php
View/Elements/formsSearch/formSearch_cursosInscripcion.ctp

Las matriculas se recuentan solo si son CONFIRMADAS
Se agrega filtro de estadoInscripcion en alumnos por seccion

Recuento de matriculas, y filtro de estadoInscripcion

---

View/CursosInscripcions/index.ctp
View/Elements/forms/form_inscripcion_edit.ctp
View/Matriculas/index.ctp
View/Vacantes/index.ctp

ActualizaVistas

---

Controller/EgresoController.php
Controller/InscripcionsController.php
Controller/PromocionController.php
View/Promocion/index.ctp

Egreso:
- Muestra solo la lista de alumnos del ciclo actual
Promocion:
- Muestra solo lista de alumnos del ciclo anterior
Inscripcion:
- FIX en conteo de matricula y vacantes al editar en todos los roles (contaba los cursosInscripcion por curso_id en todos los ciclos)

Egreso, Promocion, Inscripcion

---

Controller/EgresoController.php
Controller/ReubicacionController.php
View/Cursos/view.ctp
View/Elements/reubicacion_lista.ctp
View/Reubicacion/index.ctp

Solo es posible reubicar a los alumnos de un mismo año.
Realiza la cuantifiacion correspondiente en ambos cursos

Reubicacion

---

View/Cursos/view.ctp

Se modifica la logica para mostrar los botones de Egresos y Promociones.
Ingresa al tintero la posibilidad de configurarlo por medio de un controlador y base de datos desde el API. Y asi evitar el hardcoding en el controlador por medio de condiciones

Logica para mostrar boton Egresos y Promocion

---

Controller/CursosInscripcionsController.php
Controller/ReubicacionController.php
View/Elements/formsSearch/formSearch_cursosInscripcion.ctp

Por defecto la lista muestra los alumnos confirmados. 
Los filtros se mantienen una vez aplicados

Alumnos por seccion nominal con default en filtros

---

Controller/InscripcionsController.php
View/Elements/forms/form_inscripcion_edit.ctp
View/Elements/formsSearch/formSearch_alumno.ctp

Conteo de matriculas al inscribir, Busqueda de alumnos, Autocomplete al editar inscripcion

---

Controller/InscripcionsController.php

Si se cambia de centro respecto al centro definido en el ciclo anterior , el sistema determina que hay que generar un nuevo alumno_id

Fix en Inscripcion

---

Model/Persona.php
View/Elements/forms/form_persona_add.ctp
View/Elements/forms/form_persona_edit.ctp
View/Personas/view.ctp

PERSONA: en el formulario AGREGAR suma 2 campos, "depto_casa"y "tira_edificio". En el formulario EDICIÓN, deshabilita el campo DNI y también suma los campos, "depto_casa"y "tira_edificio". Además quita campos obligatorios.

Ajusta edición de personas

---

View/Elements/forms/form_persona_edit.ctp

Cambio de la opción "dissabled" a la opción "readonly".

Modifica el campo documento_nro

---

View/Personas/view.ctp

Modifica la visualización del DOMICILIO en el VIEW de PERSONAS.

AjustaViewDomicilio

---

Model/Inscripcion.php
View/Elements/forms/form_inscripcion_edit.ctp

Adaptación en el formulario de EDICIÓN de INSCRIPCIONES de los "motivos de baja" según el nivel. También ajusta el campo "estado de inscripción".

Ajusta motivos baja

---

README.md

Corrige el nombre del Proyecto y agrega enlace de presentación.

Actualiza el README

---

Controller/AlumnosController.php
View/Alumnos/view.ctp
View/Elements/alumno.ctp

Optimiza consultas en el View de Alumnos cuando tiene familiares relacionados.

Optimiza View del Alumno con Familiares relacionados

---

View/Elements/forms/form_inscripcion_add.ctp
View/Inscripcions/view.ctp

En el formulario de AGREGACIÓN de Inscripciones indica por defecto el "estado de inscripción" CONFIRMADA y habilita la indicación de DATOS DE ALTA. En el View, actualiza la visualización de la DOCUMENTACIÓN PRESENTADA.

AjustaInscripcionesAgregaciónView

---

Controller/CursosController.php
View/Elements/formsSearch/formSearch_curso.ctp

En el formulario de búsqueda de SECCIONES, presenta las divisiones que corresponden a la institución del usuario.

AjustaDivisionesParaBusquedaDeCursos

---

Controller/InscripcionsController.php
Controller/PersonasController.php
Model/Persona.php
View/Elements/forms/form_persona_add.ctp
View/Elements/forms/form_persona_edit.ctp
View/Inscripcions/view.ctp

Inscripcio/view obtiene datos desde la API, corrige bug de personas
Personas/add & Personas/edito optimiza seleccion de fecha con almanaque

Fix y optimizacion de Inscripcion/view y Personas Add/Edit

---

View/Inscripcions/view.ctp

Se agrega opción para imprimir constancia de alumno regular

Boton constancia de alumno regular

---

Controller/AppController.php
Controller/InscripcionsController.php
View/Centros/view.ctp
View/Elements/forms/form_inscripcion_add.ctp
View/Elements/forms/form_inscripcion_edit.ctp
View/Elements/inscripcion.ctp
View/Personas/index.ctp

Recorrido y revisión del controlador de Inscripciones, optimizando todas las consultas de las funciones ADD, EDIT y LIST. RESTA PROBAR CÓDIGO EN DESARROLLO. #313

AjustesModuloInscripciones

---

Controller/MatriculasController.php
View/Matriculas/index.ctp

Al listado SECCIÓN POR ALUMNOS NOMINAL, agrega las columnas:
- Tipo de sección (hecho).
- Varones matriculados (falta).

AgregaColumnasListadoMatrículas

---

Controller/CursosController.php
View/Cursos/view.ctp
View/Elements/forms/form_curso.ctp
View/Elements/formsSearch/formSearch_curso.ctp

Revisión de consultas y vistas del CRUD del módulo de Cursos. #314

OptimizaModuloCurso

---

Controller/CursosController.php

Se comenta la logica en el controlador

Lista de inscripciones de alumnos deshabilitada en /cursos/view

---

Controller/InscripcionsController.php
View/Elements/forms/form_inscripcion_edit.ctp

Corrige pantalla de error en Inscripciones-->Edit cuando se cambia de sección y agrega actualización de matrícula por cambio de estado de inscripción a BAJA. #313

Corrige hotfix en edit y agrega actualiza matrícula por baja

---

View/Personas/view.ctp

Habilita a un perfil "usuario" acceso a editar PERSONA.

Usuario edita Persona

---

Controller/InscripcionsController.php

Corrige bug del setFlash que informa que el alumno esta inscripto en el ciclo actual en un centro incorrecto

hotfix (bug /inscripcion/add)

---

Controller/PersonasController.php
Model/Persona.php
View/Personas/view.ctp

Resuelve:
+ En general, optimiza consultas a base de datos.
+ En ADD Y EDIT:
- Acentuaciones en mayúsculas,
- Refactorización de código,
+ En VIEW:
- Corrige el campo "Lugar de Nacimiento".

AjustaModuloPersona

---

Model/Curso.php
View/Elements/forms/form_curso.ctp

Habilita la registración de una división no predefinida.

Ajusta registración de la división

---

README.md

Test GitFlow

---

Controller/InscripcionsController.php

Cuando existe la inscripcion, el flash que lo informa no se ejecutaba correctamente, generando un 500

fix(flash en inscripcion/add)

---

Controller/InscripcionsController.php
README.md
View/Elements/cursosInscripcion_lista.ctp
View/Inscripcions/view.ctp

merge developer

---

Controller/InscripcionsController.php
View/Elements/forms/form_inscripcion_add.ctp
View/Inscripcions/view.ctp

Ajustes en el VIEW de Inscripciones del tipo "Hermano de alumno regular".

Inscripciones por hermanos

---

Controller/PasesController.php
View/Pases/view.ctp

Refactoriza código en las funciones ADD, EDIT, VIEW y LISTS. 
Optimización de consultas para mejorar rendimientos.

#325 Refactorización del controlador

---

Controller/AlumnosController.php
Controller/InscripcionsController.php
Controller/PasesController.php
View/Alumnos/view.ctp
View/Elements/forms/form_pase_edit.ctp
View/Elements/pase.ctp
View/Pases/edit.ctp

Ajustes en los módulos Inscripciones, Alumnos y Pases, para adecuar las interfaces a los procesos diferentes que utilizan Primaria y Secundaria.
Este cambio es necesario para continuar la adecuación de SIEP en relación a los procesos diferentes de PASE definidos por los niveles Inicial, Primario y Secundario. 
Continúa con los trabajos indicados en el issue #325.

#325 Ajustes para los dos procesos de pases

---

View/Alumnos/view.ctp
View/Elements/curso.ctp
View/Elements/inscripcion.ctp
View/Pases/view.ctp
View/Users/usuario.ctp

Ajustes varios en vistas que mostraban información ambigua.
Resuelve algunas ambigüedades en la información mostrada por las vistas de inicio, secciones e inscripciones.

Ajustes generales a vistas

---

Controller/PersonasController.php
Controller/UsersController.php
View/Users/usuario.ctp

Al buscar una persona, permite visualizar, sí es alumno, donde está inscripto y en que estado está.
Resuelve el problema de no poder identificar donde está inscripto un alumno o sí fué dado de baja.
Resuelve el Issue #301

#301 Agrega mensaje que indica donde está inscripto un alumno

---

Controller/UsersController.php
View/Users/usuario.ctp

Discrimina información para el usuario en el panel de inicio, según nivel.
Resuelve la utilidad del panel de inicio.

Agrega al panel de Inicio información para el usuario según el nivel.

---

Controller/PasesController.php
Model/pase.php
View/Elements/forms/form_pase_add.ctp
View/Elements/forms/form_pase_edit.ctp
View/Elements/formsSearch/formSearch_pase.ctp
View/Elements/pase.ctp
View/Pases/view.ctp

#325 Definición del MVC Pases

---

Controller/PersonasController.php

Corrección del VIEW de PERSONAS para que no use la lógica de búsqueda de inscripciones para un familiar.

Corrige bug al ver una persona que es familiar

---

Controller/PersonasController.php

Modificaciones en la función ADD del controlador.

Ajusta agregación de persona

---

View/Users/usuario.ctp

Diferencia avisos para Inicial y Primaria de Secundaria. Agrega un nuevo aviso.
Resuelve publicación de información en SIEP.

Agrega aviso a Panel de Inicio

---

Controller/MatriculasController.php
Controller/VacantesController.php
Dockerfile
View/Helper/SiepHelper.php
View/Vacantes/index.ctp

Logica de recuento para matriculas y vacantes se muda al API 
Vacantes y Matriculas tienen base de consumo de API con parametros
api/matriculas/por_seccion 
Devuelve de forma cuantitativa las inscripciones del ciclo solicitado, sumando las plazas, matriculas y vacantes de sus respectivas  divisiones (El resultado no impacta en DB)

Se muda logica de recuento hacia API

---

.gitignore
Controller/VacantesController.php
Dockerfile

Corrije la ruta a los assets necesarios para visualizar debug_kit

fix(debukit)

---

Controller/VacantesController.php

Se agrega parametro de consumo de api
estado_inscripcion Confirmada y No confirmada desde cake
(por defecto el api solo muestra confirmadas)

add apiParam

---

Controller/PersonasController.php
View/Elements/forms/form_inscripcion_edit.ctp
View/Users/usuario.ctp

Agrega datos de la sección al mensaje (en el VIEW de PERSONAS) que indica dónde está inscripto el alumno en el ciclo actual.
Resuelve identificar, además del centro, la sección concreta dónde está inscripto en el ciclo actual,

Agrega sección donde está inscripto alumno

---

Controller/IngresantesController.php
View/Ingresantes/index.ctp

Base para seccion  Ingresantes 2019, muestra  inscripciones en cursos sin division

Ingresantes 2019

---

View/Elements/menues/menu-aip.ctp
View/Elements/menues/menu-sa.ctp
View/Elements/menues/menu-u.ctp

También a los "superadmin" y "usuarios".

Agrega acceso a INSCRIPCIONES 2019 a Inicial y Primaria

---

Model/Persona.php

Ajusta la validación del campo dni_numero para permitir letras (minúsculas y mayúsculas).

Adecua campo DNI número para extranjeros

---

Controller/InscripcionsController.php
View/Elements/forms/form_inscripcion_edit.ctp

Visualiza el ciclo correspondiente de la inscripción a editar.
Corrige la visualización del ciclo correcto de la inscripción que se requiere editar.

Corrige el ciclo en EDIT de INSCRIPCIONES

---

Controller/PersonasController.php
Model/Persona.php
View/Elements/forms/form_persona_add.ctp
View/Elements/forms/form_persona_edit.ctp

En ADD/EDIT de PERSONA, al agregar la fecha de nacimiento, indica la edad optimizando su cálculo.
Resuelve informar al usuario sobre la edad al momento de ingresar la fecha de nacimiento de una PERSONA y así asignarle en la INSCRIPCIÓN un año correcto.

Optimiza registro y visualización de fecha de nacimiento y edad

---

View/Elements/formsSearch/formSearch_persona.ctp

Agrega indicación de registro no existente cuando no encuentra el DNI/Nombre de la PERSONA buscada en el FORM SEARCH.
No se indicaba nada sí la búsqueda del DNI/Nombre de PERSONA no existe en base de datos.

Agrega indicación de PERSONA no existente en el FORM SEARCH

---

View/Cursos/view.ctp

En el VIEW de SECCIONES de las Salas de 4 años MÚLTIPLES, muestra el botón EGRESAR.
Las Salas de 4 años MÚLTIPLES también tienen alumnos de 5 años que egresan.

Muestra el botón de EGRESAR en las Salas de 4 años Múltiples

---

Controller/UsersController.php
View/Users/usuario.ctp

Permite que los ATEIs en su entorno visualicen los AVISOS de todos los niveles.
Los ATEIs deben tener acceso a la información de todos los niveles.

Ajusta Panel de Inicio para ATEIs

---

Controller/FamiliarsController.php

Controla al EDITAR que no se repita el Familiar.

Ajusta repetición de Familiar al EDITAR

---

Controller/CentrosController.php
Model/Centro.php
View/Centros/add.ctp
View/Centros/edit.ctp
View/Centros/view.ctp
View/Elements/centro.ctp
View/Elements/forms/form_centro_add.ctp
View/Elements/forms/form_centro_edit.ctp
View/Elements/menues/menu-sa.ctp

Ajustes de permisos y visualizaciones en EDIT/VIEW de CENTROS para que los usuarios "admin" editen datos de contacto de sus instituciones.
Los usuarios de las instituciones mantendrán actualizados los datos de contacto de sus propios centros.

Ajustes en el módulo CENTROS para que los usuarios actualicen datos de contacto de sus instituciones

---

View/Users/usuario.ctp

Muestra procesos PASO a PASO para:
- INSCRIPCIONES POR PASES
- INSCRIPCIONES ABIERTAS
- PROMOCIONES

Genera AVISOS para el PANEL DE INICIO de ADULTOS

---

View/Cursos/view.ctp
View/Inscripcions/view.ctp

Ver descripción en versión de desarrollo.

Corrige habilitar egreso en 6tos de Colegios con Bachiller/Técnico

---

Controller/CursosController.php
View/Elements/curso.ctp

Agrega información de titulaciones a las tarjetas de SECCIONES en Secundarios Común y de Adultos.
Resuelve identificar las secciones también según su orientación/especialidad.

Agrega información de titulación a tarjetas de SECCIONES

---

Controller/CursosController.php
Controller/PersonasController.php
View/Cursos/view.ctp
View/Elements/curso.ctp
View/Elements/forms/form_curso_edit.ctp

Visualiza inscripción del alumno en el ciclo actual tomando el ciclo actual de forma automática.
Resuelve el problema de actualizar el valor del ciclo actual de forma manual.

Corrige info de inscripción en el flash del VIEW de PERSONA

---

Controller/InscripcionsController.php
Controller/PersonasController.php
View/Elements/menues/menu-aip.ctp

Identifica inscripciones del tipo MATERNAL y ESPECIAL, les asigna un Código de Inscripción específico y permite que se realicen en simultáneo a las del tipo COMÚN.
Resuelve el problema de la doble inscripción entre las COMUNES y los casos de MATERNAL o ESPECIAL. Resta refactorizar código (incorporar array asociativo) para el flash de PERSONAS->VIEW.

Agrega inscripciones del tipo MATERNAL y/o ESPECIAL con las COMUNES.

---

Controller/PromocionController.php

Promociones en Marzo

---

Controller/InscripcionsController.php

Refactoriza código para lógica de inscripción por PASE en el controlador de INSCRIPCIONES.

Actualiza lógica de PASES en INSCRIPCIONES.

---

Controller/ReubicacionController.php

Sólo lista alumnos CONFIRMADOS en el listado para REUBICAR.
Corrige la diferencias entre MATRÍCULA del listado INGRESANTES 2019 y la cantidad de alumnos del listado de REUBICCAR.

Agrega filtro de estado_inscripcion a listado de alumnos para REUBICAR.

---

View/Alumnos/view.ctp
View/Vacantes/index.ctp

Se corrige el llamado a la variable de entorno que apunta al INGRESS del API

hotfix(Imprimir Ficha de Alumno)

---

View/Elements/forms/form_inscripcion_edit.ctp

No se visualizaban los ciclos anteriores.

Corrige visualización del ciclo en la edición de inscripciones.

---

Controller/PersonasController.php

Corrige y refactoriza código del mensaje flash en el VIEW PERSONAS que informa sobre las inscripciones actuales del alumno.
Resuelve los casos de inscripciones múltiples por pase.

Corrige flash del VIEW de PERSONAS sobre inscripciones actuales.

---

View/Cursos/view.ctp
View/Elements/curso.ctp
View/Elements/cursosInscripcion_lista.ctp
View/Elements/formsSearch/formSearch_curso.ctp
View/Ingresantes/index.ctp
View/Inscripcions/view.ctp
View/Vacantes/index.ctp

Redenominaciones de nomenclaturas en tarjetas, formularios y encabezados de columnas.
#574

Adapta entorno para Modalidad Especial.

---

Model/Curso.php
View/Cursos/view.ctp
View/Elements/curso.ctp
View/Elements/cursosInscripcion_lista.ctp
View/Elements/formsSearch/formSearch_curso.ctp
View/Ingresantes/index.ctp
View/Inscripcions/view.ctp
View/Vacantes/index.ctp

 Adapta entorno para Modalidad Especial.

---

Controller/ListaAlumnosController.php
View/ListaAlumnos/index.ctp

Solo admin y superadmin pueden actualizar estados

fix Permisos updateFamiliar

---

Model/Curso.php
View/Cursos/view.ctp
View/Elements/forms/form_curso_add.ctp
View/Elements/forms/form_curso_edit.ctp
View/Vacantes/index.ctp

Habilita la indicación de la existencia de Pareja Pedagógica y/o Maestra Integradora en las secciones.
Resuelve la visualización de estas opciones que justifican la reducción de su matrícula.

habilita agregar/editar/ver opciones de configuración de cursos.

---

Controller/GatewayController.php
View/Elements/cursosInscripcion_lista.ctp
View/Elements/forms/form_inscripcion_add.ctp
View/Elements/forms/form_inscripcion_edit.ctp
View/Inscripcions/view.ctp

Inscripciones consume API correctamente
Pendiente URLs de Exportacion / Ficha de Alumnos y Constancias (problemas con render Excel y PDF desde Cake)

hotfix(Consumo de API)

---

View/Elements/forms/form_inscripcion_add.ctp
View/Inscripcions/add.ctp

Redistribución de campos en el formulario y mejoras en las indicaciones para agregar los tipos de inscripciones. 
Varios usuarios presentaron dudas al agregar inscripciones por PASE y por HERMANOS.

Mejora UX al AGREGAR INSCRIPCIONES.

---

Controller/GatewayController.php
View/Alumnos/view.ctp

Se consume desde cake correctamente

hotfix(Ficha alumno)

---

Controller/InscripcionsController.php
View/Elements/forms/form_inscripcion_add.ctp
View/Elements/forms/form_inscripcion_edit.ctp
View/Inscripcions/edit.ctp

Redistribución de campos en el formulario y agrega controlers al registrar BAJAS.
Varios usuarios presentaron dudas al editar inscripciones por BAJA.

Mejora UX al EDITAR INSCRIPCIONES y agrega control al ingresar BAJA.

---

Controller/ReubicacionController.php
View/Helper/SiepHelper.php

+ Consume api con validacion de XHOST correctamente
+ Se agrega formateo de respuesta de error a SiepHelper

fix(Reubicacion)

---

Controller/GatewayController.php
View/Inscripcions/view.ctp

fix(Constancia y Constancia Regular)

---

Controller/GatewayController.php
View/Elements/cursosInscripcion_lista.ctp
View/ListaAlumnos/index.ctp

Exportacion en Datos de Alumnos
Exportacion en Inscripciones
Pendiente exportacion en Vacantes

fix(Exportacion)

---

Controller/GatewayController.php
Controller/VacantesController.php
View/Vacantes/index.ctp

Es posible exportar a excel las vacantes a travez de gateway cake

hotfix(Exportacion de vacantes)

---

Controller/PromocionController.php
View/Elements/menues/menu-adminInicialPrimario.ctp
View/Elements/menues/menu-adminSecundario.ctp
View/Elements/menues/menu-superadminSistemas.ctp
View/Elements/menues/menu-u.ctp
View/Elements/menues/menu-usuario.ctp
View/Elements/menues/menu-usuarioInicialPrimario.ctp
View/Elements/menues/menu-usuarioSecundario.ctp
View/Promocion/view.ctp

Consume lista de promocionados desde el API y agrega al menu la opcion "Ver/Promocionados" ciclo 2018

Se agrega Lista de Promocionados

---

View/Users/usuario.ctp

Actualiza la información brindada sobre los procesos de inscripciones desde el menú VER --> PROCESOS PASO A PASO.

Actualiza información sobre procesos de inscripciones.

---

View/Promocion/view.ctp
View/Repitentes/view.ctp
View/Users/usuario.ctp

Corrige cabezera de columnas en los views de Repitentes y Promocionados.

---

Controller/InscripcionsController.php
View/Inscripcions/view.ctp

Se refactoriza el metodo Inscripcion/view

Inscripcion/view con API v2

---

Controller/IngresantesController.php
View/Elements/menues/menu-admin.ctp
View/Elements/menues/menu-adminInicialPrimario.ctp
View/Elements/menues/menu-adminSecundario.ctp
View/Elements/menues/menu-superadminSistemas.ctp
View/Elements/menues/menu-u.ctp
View/Elements/menues/menu-usuario.ctp
View/Elements/menues/menu-usuarioInicialPrimario.ctp
View/Elements/menues/menu-usuarioSecundario.ctp
View/Ingresantes/index.ctp

Habilita en menu->ver la seccion Ingresantes 2020

Ingresantes 2020

---

View/Inscripcions/view.ctp

Se remueve temporalmente la verificacion de ciclo para mostrar las opciones de imprimir constancias

hotfix Constancias en (Inscripcion/View) 

---

Controller/PromocionController.php
View/Elements/promocion_lista.ctp

Escribe en la columna promocion_id

fix Promocion

---

Controller/CursosController.php
View/Cursos/view.ctp
View/ListaAlumnos/index.ctp

La lista de datos alumnos en los cursos sin division muestran alumnos del ciclo posterior

fix ListaAlumnos

---

Controller/ListaAlumnosController.php

fix DatosAlumnos

---

Controller/CursosController.php
Controller/CursosInscripcionsController.php
Controller/GraficosController.php
View/Elements/menues/menu-adminInicialPrimario.ctp
View/Elements/menues/menu-adminSecundario.ctp
View/Graficos/index.ctp

Agrega dashboard para visualizar las principales variables cuantitativas y ordenar accesos a los datos nominales que representan.

Agrega TABLERO 2019.

---

View/Elements/forms/form_inscripcion_add.ctp

Según Calendario Escolar de niveles y situaciones particulares, habilita o deshabilta tipo de inscripciones en instituciones.

Agrega reestricción a tipos de inscripciones.

---

Controller/InscripcionsController.php
Model/Inscripcion.php
View/Elements/forms/form_inscripcion_add.ctp
View/Elements/forms/form_inscripcion_edit.ctp
View/Elements/formsSearch/formSearch_inscripcion.ctp
View/Elements/menues/menu-adminInicialPrimarioEspecial.ctp
View/Inscripcions/view.ctp
View/Layouts/default.ctp

Agrega indicación del estado del CUD (Código Único Discapacidad) al AGREGAR y EDITAR INSCRIPCIONES. Además habilita a usuarios de ESPECIAL, en el INDEX de INSCRIPCIONES, realizar búsqueda de inscripciones según el estado del CUD.
Los usuarios de la modalidad ESPECIAL, necesitan identificar los estados de los CUD de los alumnos.

Ajustes generales para la UX de la modalidad ESPECIAL.

---

View/Ingresantes/index.ctp

Se agrega visualizacion de total de inscripciones confirmadas por seccion.

Add columna Confirmadas en Ingresantes 2020

---

Model/Curso.php
View/Cursos/view.ctp
View/Elements/forms/form_curso_add.ctp
View/Elements/forms/form_curso_edit.ctp

Agrega funcionalidad que permitirá imprimir desde las instituciones, información de las SECCIONES a modo de DDJJ.
Agilizar el trámite administrativo de la Supervisión de Secundaria para obtener éste tipo de DDJJ.

Agrega campos en SECCIONES para DDJJ de Secundaria.

---

Controller/InscripcionsController.php
View/Cursos/view.ctp
View/Elements/forms/form_inscripcion_add.ctp
View/Elements/forms/form_inscripcion_edit.ctp
View/Inscripcions/view.ctp

Revert "Ajusta Entorno para el IPI."

---

Controller/GraficosController.php
View/Elements/menues/menu-superadminSistemas.ctp
View/Elements/menues/menu-usuario.ctp
View/Elements/menues/menu-usuarioInicialPrimario.ctp
View/Elements/menues/menu-usuarioSecundario.ctp
View/Graficos/index.ctp

Permite seleccionar una institución para ver el Tablero específico.

Habilita Tablero a usuarios con roles "superadmin, admin y usuarios".

---

Controller/InscripcionsController.php
Model/Inscripcion.php
View/Elements/forms/form_inscripcion_add.ctp
View/Elements/formsSearch/formSearch_inscripcion.ctp

Permite seleccionar una institución para ver el Tablero específico.

Agrega a opciones de Inscripción tipo "Estudiante de Intercambio".

---

Controller/AlumnosController.php
Controller/GatewayController.php
Model/Alumno.php
View/Alumnos/edit_constancia.ctp
View/Inscripcions/preview.ctp
View/Inscripcions/view.ctp

- Agrega Preview de impresión de constancia de alumno regular, esto permite editar algunos campos antes de imprimir dicha constancia (Por el momento solo se pueden editar las observaciones del alumno)

Edición de Constancia de Alumno Regular

---

View/Inscripcions/preview.ctp

- Quita restricción de rol para visualizar el botón de generación de PDF para constancia de alumno regular.

Impresión de Constancia de alumno regular
